//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketTill
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SupermarketContainer : DbContext
    {
        public SupermarketContainer()
            : base("name=SupermarketContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EverydayItems> EverydayItems { get; set; }
        public virtual DbSet<OffLicense> OffLicenses { get; set; }
        public virtual DbSet<DeliFood> DeliFoods { get; set; }
    }
}
